import type { AvatarOptions, AvatarEvent, AvatarEventCallback, AvatarPlugin, AvatarPosition, AvatarFraming, AvatarTheme, FramingSliceConfig, Expression, AvatarState } from "./types/index.js";
import type { Viseme } from "./audio/LipSync.js";
export declare class Avatar {
    private readonly options;
    private readonly events;
    private readonly renderer;
    private readonly animation;
    private readonly audio;
    private readonly lipSync;
    private readonly loader;
    private readonly plugins;
    constructor(options?: AvatarOptions);
    private _initialize;
    private _bindContainerEvents;
    private _boundMouseLook;
    private _bindMouseLook;
    debugBones(visible?: boolean): this;
    show(): this;
    hide(): this;
    destroy(): void;
    move(x: number, y: number): this;
    position(preset: AvatarPosition): this;
    frame(preset: AvatarFraming): this;
    setFramingConfig(config: FramingSliceConfig): this;
    setTheme(theme: AvatarTheme): this;
    scale(factor: number): this;
    size(px: number): this;
    expression(expr: Expression, intensity?: number): this;
    smile(): this;
    sad(): this;
    happy(): this;
    angry(): this;
    surprised(): this;
    thinking(): this;
    confused(): this;
    sleep(): this;
    idle(): this;
    wave(): this;
    nod(): this;
    yes(): this;
    no(): this;
    shakeHead(): this;
    clap(): this;
    jump(): this;
    dance(): this;
    thumbsUp(): this;
    private _gesture;
    lookAtMouse(): this;
    lookAt(x: number, y: number): this;
    lookForward(): this;
    randomLook(): this;
    talk(audio: AudioBuffer | ArrayBuffer | string): Promise<this>;
    startTalking(): this;
    stopTalking(): this;
    pauseTalking(): this;
    setViseme(viseme: Viseme): this;
    setMouth(shape: number): this;
    setVolume(volume: number): this;
    setState(state: AvatarState): this;
    loading(): this;
    success(): this;
    error(): this;
    warning(): this;
    typing(): this;
    listening(): this;
    processing(): this;
    complete(): this;
    clearState(): this;
    play(name: string): this;
    stop(): this;
    load(model: string): Promise<this>;
    on(event: AvatarEvent, callback: AvatarEventCallback): this;
    off(event: AvatarEvent, callback: AvatarEventCallback): this;
    use(plugin: AvatarPlugin, options?: Record<string, unknown>): this;
}
//# sourceMappingURL=Avatar.d.ts.map